# Generated by Django 4.2.27 on 2025-12-18 02:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('crd', models.DateField(blank=True, null=True, verbose_name='CRD')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='ETD')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ERP Order',
                'verbose_name_plural': 'ERP Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmuk_item_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='BMUK Item No.')),
                ('mtl_ref_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='MTL Ref NO.')),
                ('prism_code', models.CharField(blank=True, max_length=50, verbose_name='PRISM Code')),
                ('sub_category', models.CharField(max_length=100, verbose_name='Sub Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('product_specification', models.TextField(blank=True, verbose_name='Product Specification')),
                ('care_information', models.TextField(blank=True, verbose_name='Care Information')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Image')),
                ('product_category', models.CharField(max_length=100, verbose_name='Product Category / Age Grade')),
                ('material_type', models.CharField(choices=[('plastic', 'Plastic'), ('fabric', 'Fabric'), ('cosmetic', 'Cosmetic'), ('wood', 'Wood'), ('slime', 'Slime'), ('paper', 'Paper'), ('paint', 'Paint'), ('crayon', 'Crayon'), ('dough', 'Dough'), ('other', 'Other')], max_length=50, verbose_name='Material Type')),
                ('new_repeat_status', models.CharField(choices=[('repeat', 'Repeat from direct supplier'), ('new_item', 'New item# or Direct Import'), ('new_supplier', 'Change supplier/manufacturer')], max_length=100, verbose_name='New/Repeat Status')),
                ('supplier_code', models.CharField(max_length=50, verbose_name='Supplier Code')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('factory_item_no', models.CharField(blank=True, max_length=50, verbose_name='Factory Item No.')),
                ('bm_fr_item_no', models.CharField(blank=True, max_length=50, verbose_name='BM FR Item No.')),
                ('fob_port', models.CharField(max_length=100, verbose_name='FOB Port')),
                ('merchandiser_name', models.CharField(max_length=200, verbose_name='Merchandiser')),
                ('merchant_enquiry_date', models.DateField(verbose_name='Merchant Enquiry Date')),
                ('shipdate_crd', models.DateField(verbose_name='Shipdate CRD')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Order Number')),
                ('shipment_id', models.CharField(blank=True, max_length=50, verbose_name='Shipment ID')),
                ('test_requirements', models.TextField(blank=True, verbose_name='Test Requirements')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_qa_products', to=settings.AUTH_USER_MODEL, verbose_name='QA In-charge')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_qa_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-merchant_enquiry_date'],
            },
        ),
        migrations.CreateModel(
            name='TestRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('bsen71_1', 'BSEN 71-1'), ('bsen71_2', 'BSEN 71-2'), ('bsen71_3', 'BSEN 71-3'), ('cadmium', 'Total Cadmium (REACH Entry 23)'), ('phthalates', 'Phthalates (REACH Entry 51 & 52)'), ('pahs', 'PAHs (REACH Entry 50)'), ('sccp', 'SCCP (POPs regulation)'), ('reach_svhc', 'REACH SVHC'), ('csa', 'CSA/Risk Assessment'), ('other', 'Other Test')], max_length=50, verbose_name='Test Name')),
                ('requirement_description', models.TextField(blank=True, verbose_name='Requirement Description')),
                ('test_status', models.CharField(choices=[('ok', 'OK'), ('awaiting', 'Awaiting'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Test Status')),
                ('its_reference_number', models.CharField(blank=True, max_length=50, verbose_name='ITS Reference Number')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Test Date')),
                ('required_for_stage', models.CharField(blank=True, choices=[('R', 'Report/Test Plan'), ('A', 'Artwork Review'), ('F', 'Factory Sample'), ('M', 'Mockup/Red Sample'), ('G', 'Gold Seal/Shipment Sample')], max_length=1, verbose_name='Required For Stage')),
                ('compliance_notes', models.TextField(blank=True, verbose_name='Compliance Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_requirement_items', to='qa_app.product')),
            ],
            options={
                'verbose_name': 'Test Requirement',
                'verbose_name_plural': 'Test Requirements',
                'ordering': ['product', 'test_name'],
            },
        ),
        migrations.CreateModel(
            name='ERPShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('shipment_status', models.CharField(blank=True, max_length=50)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='qa_app.erporder')),
            ],
            options={
                'verbose_name': 'ERP Shipment',
                'verbose_name_plural': 'ERP Shipments',
            },
        ),
        migrations.AddField(
            model_name='erporder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_orders', to='qa_app.product'),
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('test_report', 'Test Report'), ('doi', 'Declaration of Innocence (DOI)'), ('csa', 'Chemical Safety Assessment (CSA)'), ('bom', 'Bill of Materials (BOM)'), ('doc', 'Declaration of Compliance (DOC)'), ('svhc', 'REACH SVHC Certificate'), ('other', 'Other Document')], max_length=20, verbose_name='Document Type')),
                ('test_name', models.CharField(blank=True, max_length=200, verbose_name='Test Name')),
                ('its_reference', models.CharField(blank=True, max_length=50, verbose_name='ITS Reference')),
                ('test_result', models.CharField(blank=True, choices=[('ok', 'OK'), ('failed', 'Failed'), ('pending', 'Pending'), ('na', 'N/A')], max_length=20, verbose_name='Test Result')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Test Date')),
                ('last_update_date', models.DateField(verbose_name='Last Update Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('document_file', models.FileField(upload_to='compliance_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'png'])], verbose_name='Document File')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='qa_app.product')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Compliance Document',
                'verbose_name_plural': 'Compliance Documents',
                'ordering': ['-last_update_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('R', 'Report/Test Plan'), ('A', 'Artwork Review'), ('F', 'Factory Sample'), ('M', 'Mockup/Red Sample'), ('G', 'Gold Seal/Shipment Sample')], max_length=1, verbose_name='Stage Type')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('rejected', 'Rejected')], default='not_started', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_stages', to='qa_app.product')),
            ],
            options={
                'verbose_name': 'Product Stage',
                'verbose_name_plural': 'Product Stages',
                'ordering': ['product', 'stage_type'],
                'unique_together': {('product', 'stage_type')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'merchant_enquiry_date'], name='qa_app_prod_status_f51343_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['assigned_user', 'status'], name='qa_app_prod_assigne_87a0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['order_number'], name='qa_app_prod_order_n_f99d96_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['mtl_ref_no'], name='qa_app_prod_mtl_ref_979c06_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['bmuk_item_no'], name='qa_app_prod_bmuk_it_ac1e6d_idx'),
        ),
    ]
