# Generated by Django 4.2.27 on 2026-01-22 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('customer', models.CharField(max_length=200)),
                ('supplier', models.CharField(max_length=200)),
                ('cargo_ready_date', models.DateField(db_index=True)),
                ('gm_order_no', models.CharField(blank=True, max_length=100)),
                ('bm_item_no', models.CharField(blank=True, max_length=100)),
                ('product_description', models.TextField()),
                ('order_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=200)),
                ('stage_order', models.IntegerField()),
                ('days_before_crd', models.IntegerField(default=60, help_text='Number of days before CRD this task should be completed')),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='orders.workflowtemplate')),
            ],
            options={
                'ordering': ['stage_order'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_email_enabled', models.BooleanField(default=True)),
                ('daily_email_time', models.TimeField(default='09:00')),
                ('send_warning_alerts', models.BooleanField(default=True)),
                ('send_critical_alerts', models.BooleanField(default=True)),
                ('show_completed_tasks', models.BooleanField(default=False)),
                ('default_view', models.CharField(choices=[('my_tasks', 'My Tasks'), ('all_orders', 'All Orders'), ('team', 'Team View')], default='my_tasks', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(db_index=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('alert_status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning (7 days)'), ('critical', 'Critical (Overdue)')], db_index=True, default='normal', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.order')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.workflowstage')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cargo_ready_date'], name='orders_orde_cargo_r_ca4b23_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstage',
            index=models.Index(fields=['template', 'stage_order'], name='orders_work_templat_8d3105_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstage',
            unique_together={('template', 'stage_order')},
        ),
        migrations.AddIndex(
            model_name='ordertask',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_dcde66_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertask',
            index=models.Index(fields=['assigned_to', 'status'], name='orders_orde_assigne_13f62d_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertask',
            index=models.Index(fields=['alert_status'], name='orders_orde_alert_s_50a90b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertask',
            index=models.Index(fields=['planned_date'], name='orders_orde_planned_bad07e_idx'),
        ),
    ]
