# Generated by Django 4.2.27 on 2026-02-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_wip_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_column='ProductId', max_length=30, unique=True)),
                ('barcode', models.TextField(blank=True, db_column='Barcode', null=True)),
                ('customer_item_code', models.CharField(blank=True, db_column='CustomerItemCode', max_length=30, null=True)),
                ('supplier_item_code', models.CharField(blank=True, db_column='SupplierItemCode', max_length=30, null=True)),
                ('department_no', models.CharField(blank=True, db_column='DepartmentNo', max_length=10, null=True)),
                ('packing', models.CharField(blank=True, db_column='Packing', max_length=100, null=True)),
                ('material', models.CharField(blank=True, db_column='Material', max_length=50, null=True)),
                ('brand', models.CharField(blank=True, db_column='Brand', max_length=50, null=True)),
                ('supplier_id', models.CharField(blank=True, db_column='SupplierId', max_length=10, null=True)),
                ('product_name', models.CharField(blank=True, db_column='ProductName', max_length=100, null=True)),
                ('unit_price', models.DecimalField(blank=True, db_column='UnitPrice', decimal_places=4, max_digits=12, null=True)),
                ('unit_price1', models.DecimalField(blank=True, db_column='UnitPrice1', decimal_places=4, max_digits=12, null=True)),
                ('unit_price2', models.DecimalField(blank=True, db_column='UnitPrice2', decimal_places=4, max_digits=12, null=True)),
                ('unit_cost', models.DecimalField(blank=True, db_column='UnitCost', decimal_places=4, max_digits=12, null=True)),
                ('qty_per_carton', models.IntegerField(blank=True, db_column='QtyPerCarton', null=True)),
                ('carton_unit', models.CharField(blank=True, db_column='CartonUnit', max_length=10, null=True)),
                ('per_carton_unit', models.CharField(blank=True, db_column='PerCartonUnit', max_length=10, null=True)),
                ('per_carton_qty', models.DecimalField(blank=True, db_column='PerCartonQty', decimal_places=4, max_digits=12, null=True)),
                ('length', models.DecimalField(blank=True, db_column='Length', decimal_places=4, max_digits=12, null=True)),
                ('hight', models.DecimalField(blank=True, db_column='Hight', decimal_places=4, max_digits=12, null=True)),
                ('width', models.DecimalField(blank=True, db_column='Width', decimal_places=4, max_digits=12, null=True)),
                ('measure_unit', models.CharField(blank=True, db_column='MeasureUnit', max_length=10, null=True)),
                ('cuft', models.DecimalField(blank=True, db_column='CUFT', decimal_places=6, max_digits=14, null=True)),
                ('cbm', models.DecimalField(blank=True, db_column='CBM', decimal_places=6, max_digits=14, null=True)),
                ('net_wt', models.DecimalField(blank=True, db_column='NetWt', decimal_places=4, max_digits=12, null=True)),
                ('gross_wt', models.DecimalField(blank=True, db_column='GrossWt', decimal_places=4, max_digits=12, null=True)),
                ('main_category_id', models.CharField(blank=True, db_column='MainCategoryId', max_length=50, null=True)),
                ('sub_category_id', models.CharField(blank=True, db_column='SubCategoryId', max_length=10, null=True)),
                ('hs_code', models.CharField(blank=True, db_column='HSCode', max_length=20, null=True)),
                ('inactive', models.BooleanField(blank=True, db_column='Inactive', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='CreateTime', null=True)),
                ('create_by', models.CharField(blank=True, db_column='CreateBy', max_length=20, null=True)),
                ('mod_time', models.DateTimeField(blank=True, db_column='ModTime', null=True)),
                ('mod_by', models.CharField(blank=True, db_column='ModBy', max_length=20, null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=100, null=True)),
                ('unit_price_term', models.CharField(blank=True, db_column='UnitPriceTerm', max_length=30, null=True)),
                ('unit_price_term1', models.CharField(blank=True, db_column='UnitPriceTerm1', max_length=30, null=True)),
                ('unit_price_term2', models.CharField(blank=True, db_column='UnitPriceTerm2', max_length=30, null=True)),
                ('unit_cost_term', models.CharField(blank=True, db_column='UnitCostTerm', max_length=30, null=True)),
                ('lab_test_till_date', models.DateTimeField(blank=True, db_column='LabTestTillDate', null=True)),
            ],
            options={
                'db_table': 'PRODUCTS',
            },
        ),
        migrations.RenameIndex(
            model_name='sodetail',
            new_name='SODETAIL_SCNumbe_84e409_idx',
            old_name='orders_sod_sc_numb_1b7f97_idx',
        ),
        migrations.RenameIndex(
            model_name='sodetail',
            new_name='SODETAIL_PONumbe_24ba1b_idx',
            old_name='orders_sod_po_numb_6b0fa7_idx',
        ),
        migrations.RenameIndex(
            model_name='sodetail',
            new_name='SODETAIL_Product_21eb98_idx',
            old_name='orders_sod_product_6f8f84_idx',
        ),
        migrations.RenameIndex(
            model_name='somain',
            new_name='SOMAIN_SCNumbe_75da83_idx',
            old_name='orders_som_sc_numb_155e09_idx',
        ),
        migrations.RenameIndex(
            model_name='somain',
            new_name='SOMAIN_SCDate_86777d_idx',
            old_name='orders_som_sc_date_f0fce0_idx',
        ),
        migrations.RenameIndex(
            model_name='somain',
            new_name='SOMAIN_CRD_343a13_idx',
            old_name='orders_som_crd_4d0f8c_idx',
        ),
        migrations.RenameIndex(
            model_name='wiporder',
            new_name='orders_wipo_departm_005958_idx',
            old_name='orders_wip_departm_287476_idx',
        ),
        migrations.RenameIndex(
            model_name='wiporder',
            new_name='orders_wipo_assigne_898864_idx',
            old_name='orders_wip_assigne_7e6b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='wiptask',
            new_name='orders_wipt_planned_5c76f6_idx',
            old_name='orders_wip_planned_6d8a27_idx',
        ),
        migrations.RenameIndex(
            model_name='wiptask',
            new_name='orders_wipt_status_6481d0_idx',
            old_name='orders_wip_status_2e9d43_idx',
        ),
        migrations.RenameIndex(
            model_name='wiptypedefinition',
            new_name='orders_wipt_departm_ae8d12_idx',
            old_name='orders_wip_departm_1c83b9_idx',
        ),
        migrations.RenameIndex(
            model_name='wiptypedefinition',
            new_name='orders_wipt_lead_ti_29f9d2_idx',
            old_name='orders_wip_lead_t_f1b2c0_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowgridentry',
            new_name='orders_work_templat_b6afb0_idx',
            old_name='orders_work_templat_0f3f1e_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowgridentry',
            new_name='orders_work_assigne_b358cb_idx',
            old_name='orders_work_assigne_3a7960_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_id'], name='PRODUCTS_Product_bc6bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier_id'], name='PRODUCTS_Supplie_86ddf2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='PRODUCTS_Product_6c6b49_idx'),
        ),
    ]
