# Generated by Django 4.2.27 on 2026-02-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_column='Brand', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category_id',
            field=models.CharField(blank=True, db_column='MainCategoryId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, db_column='Material', max_length=100, null=True),
        ),
    ]
