# Generated by Django 4.2.27 on 2026-02-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_product_brand_alter_product_main_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_code', models.CharField(blank=True, db_column='PaymentTermCode', max_length=10, null=True, unique=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=100, null=True)),
                ('due_day', models.DecimalField(blank=True, db_column='DueDay', decimal_places=0, max_digits=3, null=True)),
                ('discount', models.DecimalField(blank=True, db_column='Discount', decimal_places=2, max_digits=5, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CreatedTime', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=20, null=True)),
                ('mod_time', models.DateTimeField(blank=True, db_column='ModTime', null=True)),
                ('mod_by', models.CharField(blank=True, db_column='ModBy', max_length=20, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=10, null=True)),
            ],
            options={
                'db_table': 'PaymentTerm',
                'indexes': [models.Index(fields=['term_code'], name='PaymentTerm_Payment_1fe383_idx'), models.Index(fields=['status'], name='PaymentTerm_Status_f09b71_idx')],
            },
        ),
    ]
