# Generated by Django 4.2.27 on 2026-02-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_paymentterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, db_column='CustomerId', max_length=20, null=True, unique=True)),
                ('customer_code', models.CharField(blank=True, db_column='CustomerCode', max_length=10, null=True)),
                ('salesman', models.CharField(blank=True, db_column='Salesman', max_length=10, null=True)),
                ('customer_name', models.CharField(blank=True, db_column='CustomerName', max_length=60, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='ContactPerson', max_length=30, null=True)),
                ('address1', models.CharField(blank=True, db_column='Address1', max_length=60, null=True)),
                ('address2', models.CharField(blank=True, db_column='Address2', max_length=60, null=True)),
                ('address3', models.CharField(blank=True, db_column='Address3', max_length=60, null=True)),
                ('address4', models.CharField(blank=True, db_column='Address4', max_length=60, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=10, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=40, null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=40, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='PostalCode', max_length=10, null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=40, null=True)),
                ('tel1', models.CharField(blank=True, db_column='Tel1', max_length=40, null=True)),
                ('tel2', models.CharField(blank=True, db_column='Tel2', max_length=40, null=True)),
                ('contact_person1', models.CharField(blank=True, db_column='ContactPerson1', max_length=40, null=True)),
                ('contact_person2', models.CharField(blank=True, db_column='ContactPerson2', max_length=40, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=40, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=40, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=80, null=True)),
                ('payment_term', models.CharField(blank=True, db_column='PaymentTerm', max_length=10, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=10, null=True)),
                ('ship_to', models.CharField(blank=True, db_column='ShipTo', max_length=10, null=True)),
                ('trade_term', models.CharField(blank=True, db_column='TradeTerm', max_length=30, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CreatedTime', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=30, null=True)),
                ('mod_time', models.DateTimeField(blank=True, db_column='ModTime', null=True)),
                ('mod_by', models.CharField(blank=True, db_column='ModBy', max_length=30, null=True)),
                ('port_of_loading', models.CharField(blank=True, db_column='PortofLoading', max_length=10, null=True)),
                ('po_remark', models.CharField(blank=True, db_column='PORemark', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'indexes': [models.Index(fields=['customer_id'], name='Customer_Custome_1d9604_idx'), models.Index(fields=['customer_code'], name='Customer_Custome_2ed0a0_idx'), models.Index(fields=['customer_name'], name='Customer_Custome_f5b940_idx')],
            },
        ),
    ]
