# Generated by Django 4.2.27 on 2026-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='po_remark',
            field=models.TextField(blank=True, db_column='PORemark', null=True),
        ),
    ]
