# Generated by Django 4.2.27 on 2026-02-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_customer_po_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(db_column='DepartmentId', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, db_column='DepartmentName', max_length=100, null=True),
        ),
    ]
