# Generated by Django 4.2.27 on 2026-02-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_department_code_alter_department_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
    ]
