# Generated by Django 4.2.27 on 2026-02-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_department_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoxUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_column='UserID', max_length=20, unique=True)),
                ('user_name', models.CharField(blank=True, db_column='UserName', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=20, null=True)),
                ('mod_time', models.DateTimeField(blank=True, db_column='ModTime', null=True)),
                ('mod_by', models.CharField(blank=True, db_column='ModBy', max_length=30, null=True)),
                ('department_id', models.CharField(blank=True, db_column='DepartmentId', max_length=20, null=True)),
            ],
            options={
                'db_table': 'User',
                'indexes': [models.Index(fields=['user_id'], name='User_UserID_af9494_idx'), models.Index(fields=['department_id'], name='User_Departm_2fb338_idx')],
            },
        ),
    ]
