# Generated by Django 4.2.27 on 2026-02-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_foxuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='foxuser',
            name='department_user_level',
            field=models.CharField(blank=True, db_column='DepartmentUserLevel', max_length=20, null=True),
        ),
    ]
