# Generated by Django 4.2.27 on 2026-02-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_foxuser_department_user_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(db_column='SupplierCode', max_length=20, unique=True)),
                ('supplier_name', models.CharField(blank=True, db_column='SupplierName', max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='ContactPerson', max_length=50, null=True)),
                ('address1', models.CharField(blank=True, db_column='Address1', max_length=100, null=True)),
                ('address2', models.CharField(blank=True, db_column='Address2', max_length=100, null=True)),
                ('address3', models.CharField(blank=True, db_column='Address3', max_length=100, null=True)),
                ('address4', models.CharField(blank=True, db_column='Address4', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='PostalCode', max_length=20, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=10, null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=50, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('contact_tel1', models.CharField(blank=True, db_column='ContactTel1', max_length=50, null=True)),
                ('contact_tel2', models.CharField(blank=True, db_column='ContactTel2', max_length=50, null=True)),
                ('contact_tel3', models.CharField(blank=True, db_column='ContactTel3', max_length=50, null=True)),
                ('contact1', models.CharField(blank=True, db_column='Contact1', max_length=50, null=True)),
                ('contact2', models.CharField(blank=True, db_column='Contact2', max_length=50, null=True)),
                ('contact3', models.CharField(blank=True, db_column='Contact3', max_length=50, null=True)),
                ('payment_term', models.CharField(blank=True, db_column='PaymentTerm', max_length=10, null=True)),
                ('ship_from', models.CharField(blank=True, db_column='ShipFrom', max_length=10, null=True)),
                ('remark', models.TextField(blank=True, db_column='Remark', null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CreatedTime', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
                ('mod_time', models.DateTimeField(blank=True, db_column='ModTime', null=True)),
                ('mod_by', models.CharField(blank=True, db_column='ModBy', max_length=50, null=True)),
                ('date1', models.DateTimeField(blank=True, db_column='Date1', null=True)),
                ('audit_exp_date', models.DateTimeField(blank=True, db_column='AuditExpDate', null=True)),
                ('date3', models.DateTimeField(blank=True, db_column='Date3', null=True)),
                ('homepage', models.CharField(blank=True, db_column='Homepage', max_length=100, null=True)),
                ('contact_email1', models.CharField(blank=True, db_column='ContactEmail1', max_length=100, null=True)),
                ('contact_email2', models.CharField(blank=True, db_column='ContactEmail2', max_length=100, null=True)),
                ('contact_email3', models.CharField(blank=True, db_column='ContactEmail3', max_length=100, null=True)),
                ('audit_pass_time', models.DateTimeField(blank=True, db_column='AuditPassTime', null=True)),
                ('audit_pass_by', models.CharField(blank=True, db_column='AuditPassBy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Supplier',
                'indexes': [models.Index(fields=['supplier_code'], name='Supplier_Supplie_ba759b_idx'), models.Index(fields=['supplier_name'], name='Supplier_Supplie_326eba_idx')],
            },
        ),
    ]
