# Generated by Django 4.2.27 on 2026-04-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_wiptask_inspection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='copy_from_product_id',
            field=models.CharField(blank=True, db_column='CopyFromProductId', max_length=50, null=True),
        ),
    ]
