# Generated by Django 4.2.27 on 2026-04-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_product_copy_from_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='french_item_code',
            field=models.CharField(blank=True, db_column='FrenchItemCode', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='german_item_code',
            field=models.CharField(blank=True, db_column='GermanItemCode', max_length=30, null=True),
        ),
    ]
