# Generated by Django 4.2.27 on 2026-04-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_product_french_german_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainCategory',
            fields=[
                ('main_category_id', models.CharField(db_column='MainCategoryID', max_length=100, primary_key=True, serialize=False)),
                ('main_category_name', models.CharField(blank=True, db_column='MainCategoryName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Product_Main_CAT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('sub_category_id', models.CharField(db_column='SubCategoryID', max_length=100, primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(blank=True, db_column='SubCategoryName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Product_Sub_Cat',
                'managed': False,
            },
        ),
    ]
