# Generated by Django 4.2.27 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_product_french_german_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, db_column='Status', max_length=10, null=True),
        ),
    ]

