# Generated by Django 4.2.27 on 2026-04-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_productmaincategory_productsubcategory'),
        ('orders', '0019_supplier_status'),
    ]

    operations = [
    ]
