# Generated by Django 4.2.30 on 2026-04-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_merge_20260421_1732'),
        ('orders', '0020_merge_20260421_1733'),
    ]

    operations = [
    ]
