# Generated by Django 4.2.27 on 2026-04-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_merge_20260421_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='somain',
            name='charge1_amount',
            field=models.DecimalField(blank=True, db_column='Charge1Amount', decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge1_cur_rate',
            field=models.DecimalField(blank=True, db_column='Charge1CurRate', decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge1_currency',
            field=models.CharField(blank=True, db_column='Charge1Currency', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge1_desc',
            field=models.CharField(blank=True, db_column='Charge1Desc', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge2_amount',
            field=models.DecimalField(blank=True, db_column='Charge2Amount', decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge2_cur_rate',
            field=models.DecimalField(blank=True, db_column='Charge2CurRate', decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge2_currency',
            field=models.CharField(blank=True, db_column='Charge2Currency', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge2_desc',
            field=models.CharField(blank=True, db_column='Charge2Desc', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge3_amount',
            field=models.DecimalField(blank=True, db_column='Charge3Amount', decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge3_cur_rate',
            field=models.DecimalField(blank=True, db_column='Charge3CurRate', decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge3_currency',
            field=models.CharField(blank=True, db_column='Charge3Currency', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge3_desc',
            field=models.CharField(blank=True, db_column='Charge3Desc', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge4_amount',
            field=models.DecimalField(blank=True, db_column='Charge4Amount', decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge4_cur_rate',
            field=models.DecimalField(blank=True, db_column='Charge4CurRate', decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge4_currency',
            field=models.CharField(blank=True, db_column='Charge4Currency', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='charge4_desc',
            field=models.CharField(blank=True, db_column='Charge4Desc', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='inv_total_amount',
            field=models.DecimalField(blank=True, db_column='InvTotalAmount', decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='po_currency',
            field=models.CharField(blank=True, db_column='POCurrency', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='po_total_amount',
            field=models.DecimalField(blank=True, db_column='POTotalAmount', decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='sc_currency',
            field=models.CharField(blank=True, db_column='SCCurrency', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='somain',
            name='sc_ex_rate',
            field=models.DecimalField(blank=True, db_column='SCExRate', decimal_places=6, max_digits=11, null=True),
        ),
    ]
