# Generated by Django 4.2.27 on 2026-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_somain_charge1_amount_somain_charge1_cur_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sodetail',
            name='item_currency',
            field=models.CharField(blank=True, db_column='ItemCurrency', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sodetail',
            name='material_name',
            field=models.CharField(blank=True, db_column='MaterialName', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sodetail',
            name='sc_item_photo',
            field=models.CharField(blank=True, db_column='SCItemPhoto', max_length=80, null=True),
        ),
    ]
